language: java
os: linux
jdk: openjdk8
services:
  - docker

cache:
  directories:
    - "$HOME/.m2"

matrix:
  include:
   - os: linux
     arch: amd64
     env:
       - DOCKER_FILE=./docker/Dockerfile
       - IMAGE_NAME=squote
   - os: linux
     arch: arm64
     env:
       - DOCKER_FILE=./docker/Dockerfile-arm64
       - IMAGE_NAME=squote-arm64

before_install:
  - chmod +x mvnw

before_script:
  - docker run -d -p 27017:27017 mongo

script:
  - export MONGO_HOST=localhost:27017
  - ./mvnw resources:resources package

deploy:
  cleanup: false
  provider: script
  script: docker/docker_build_push.sh
  on:
    branch: travisci-arm64
