language: java
os: linux
jdk: openjdk8
services:
  - docker

cache:
  directories:
    - "$HOME/.m2"

matrix:
  include:
   - os: linux
     arch: amd64
     env:
       - DOCKER_FILE=./Dockerfile
       - IMAGE_NAME=squote
   - os: linux
     arch: arm64
     env:
       - DOCKER_FILE=./Dockerfile-arm64
       - IMAGE_NAME=squote-arm64

before_install:
  - chmod +x mvnw

before_script:
  - docker run -d -p 27017:27017 mongo

script:
  - export MONGO_HOST=localhost:27017
  - ./mvnw resources:resources package

deploy:
  provider: script
  script:
    - docker build -t thcathy/${IMAGE_NAME}:latest -t thcathy/${IMAGE_NAME}:$TAG -f ${DOCKER_FILE}
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker push thcathy/${IMAGE_NAME}:latest
    - docker push thcathy/${IMAGE_NAME}:$TAG
  on:
    branch: travisci-arm64
