language: java

cache:
  directories:
    - "$HOME/.m2"
    
jdk: openjdk8

services:
  - docker

env:
  - MONGO_HOST=localhost:27017
  
before_script:
  - docker run -d -p 27017:27017 mongo

deploy:
  on:
    branch: master
