version: 2
jobs:
  build:    
    working_directory: ~/code
    docker:
      - image: circleci/openjdk:10-jdk-node-browsers
      - image: circleci/mongo
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: maven-{{ checksum "pom.xml" }}      
      - run: mvn dependency:go-offline      
      - save_cache:
          paths:
            - ~/.m2
          key: maven-{{ checksum "pom.xml" }}
      - run: mvn resources:resources package      
      - store_test_results:
          path: target/surefire-reports      
      - store_artifacts:
          path: target/esl.jar
      - persist_to_workspace:
          root: ~/
          paths: 
            - code
  deploy:
    working_directory: ~/code
    docker:
      - image: circleci/openjdk:10-jdk-node-browsers
    steps:      
      - attach_workspace:
          at: ~/
      - setup_remote_docker
      - run: |
          TAG=1.0.$CIRCLE_BUILD_NUM         
          docker build -t thcathy/squote:latest -t thcathy/squote:$TAG .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push thcathy/squote:latest
          docker push thcathy/squote:$TAG
workflows:
  version: 2
  commit-workflow:
    jobs:
      - build 
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
  scheduled-workflow:
    triggers:
      - schedule:
          cron: "30 5 * * 5"
          filters:
            branches:
              only: 
                - master
    jobs:
      - build
