spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_HOST}/squote
  mail:
    host: ENC(QFdjEhb2wr4YW6y55kwhOAJPbG3zqCrpCFhnZtVLVVHnS+9ls7O9Qd6dH0TmgoUk)
    port: ENC(ZoAUR8C7Rhb3wursBftSfsQ7bfFrQSyEYRLFXgmhJ+L0zIFtLQR0tB1g+AeN5O0s)
    username: ENC(ToT5Lf2KIZqwR6xa6u95y+hOKNrC2n52pCuOah2NLtWxY5BjSPvnR27pVEyJ5x3dhT4T7UhQV0T/tp+2vkbO7w==)
    password: ENC(vshHpDEnUcNhw2E61Fn955bwp6wZhRAzH8mNI7Zke33VFqx68J3PxXvsjc7B2d/8Sy5Inei0aZycXqchLgu+6Q==)
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

build:
  timestamp: '@mavenBuildTimestamp@'

server:
  port: 8080

auth0:
  cert: /auth0.pem
  audience: ENC(6WHzsczsXYbFH5qld+COuOuG2EoVNr4h2N2l86c+kmEEG/yao/r6rxTAidPMvp0vudow79XdwGND42rWpRBR6vytdSqlBRIe4AmhP2t/c1c=)

binance:
  apikey: ENC(hKK/0HzU+XKYVHmMr1lUE++UaUiXFmVs3SKBiOtIrTEB2cAhcZinV8RJHEtzsw1sMsS7zfTxkkNa5zRU068qr4HQ256dag8B/NZwTCC1GzlI2DeGgTgOQdO/xsYQP9qpLRWdLYzOifKFIo01zRv3zQ==)
  apisecret: ENC(3FQgjA75ZWQdKa8GxxnNA5ZoCNUZTRiRtqp7e3bG0AhKPUnOGu4Uhg2PHSTWXNW0m+Mr9JVc4T5o/GSMNWBKoq6gWP9MtOeyrBO1jSB/37mDeD2dPh/oj1p0sfPNnFYRaPWGjXmILwx0HnTCDRNrvA==)

syncstockexecutionstask:
  userId: 'ENC(0TMR4CMt1UaDKj0YxVU5WrsLgOo7/+3en6fWwwpu54OdViKdBjImlKP1JLMq7PrRMdbMjegACHEqgL6dKnNoVH9H6gjPMJOICSMmvDqoQI8=)'
  enabled: true

calculatedailysummarytask:
  enabled: true
  stdDevRange: 20,30
  codes: 2800,3020,2840

stocktradingtask:
  enabled: false
  stdDevRange: 20
  stdDevMultiplier: 0.95
  fundSymbols:
    newfund:
      - 2800

futuOpendRsaKey: '${FUTUOPEND_RSAKEY:dummy}'
futuClientConfigsJson: 'ENC(1zzpuBjL0Cma99asiL6doVxydXB2+EQ8Yu/shVMwfH+B//WhSb/lxvJK7pfIfBu573BkiFqaCDY/pI/7+QWa4e3A/L1uxQC4x9BxVMdLA75QvJaR3x17t42dSn9XsQnSwkZBA5p5KsCHQ/vHhlnCSRvG+B6CON5e7gpQwBVpCr3IDpbYTjOmmdU8pY9EK+TWhhcWgSFqfby/Aj+ByAJwDNspJw/QlRafzgB8rDDRtZhoEfjFN0COB89e8e67w0rmIEswxAS5SosusV+zj1rDMKGX94lU4AFYz5dzNyXgjlYoB3YlloHM4r2zeF/I/A7fZkDMwEptp/T2dMPcqgZ+mvSG4wErGKX7PJ8GyDjvW86bN4D6Wf5jJjDVen3TyBBgSzFGNdJUTQJIg0u0O1wU9UgBSnPerkjzCgFQHG0woBkNZ1Znj8MUuahnOKy/vkXg)'
