spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_HOST}/squote
  mail:
    host: ENC(QFdjEhb2wr4YW6y55kwhOAJPbG3zqCrpCFhnZtVLVVHnS+9ls7O9Qd6dH0TmgoUk)
    port: ENC(ZoAUR8C7Rhb3wursBftSfsQ7bfFrQSyEYRLFXgmhJ+L0zIFtLQR0tB1g+AeN5O0s)
    username: ENC(ToT5Lf2KIZqwR6xa6u95y+hOKNrC2n52pCuOah2NLtWxY5BjSPvnR27pVEyJ5x3dhT4T7UhQV0T/tp+2vkbO7w==)
    password: ENC(vshHpDEnUcNhw2E61Fn955bwp6wZhRAzH8mNI7Zke33VFqx68J3PxXvsjc7B2d/8Sy5Inei0aZycXqchLgu+6Q==)
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

build:
  timestamp: '@mavenBuildTimestamp@'

server:
  port: 8080

auth0:
  cert: /auth0.pem
  audience: ENC(6WHzsczsXYbFH5qld+COuOuG2EoVNr4h2N2l86c+kmEEG/yao/r6rxTAidPMvp0vudow79XdwGND42rWpRBR6vytdSqlBRIe4AmhP2t/c1c=)

binance:
  apikey: 'ENC(hKK/0HzU+XKYVHmMr1lUE++UaUiXFmVs3SKBiOtIrTEB2cAhcZinV8RJHEtzsw1sMsS7zfTxkkNa5zRU068qr4HQ256dag8B/NZwTCC1GzlI2DeGgTgOQdO/xsYQP9qpLRWdLYzOifKFIo01zRv3zQ==)'
  apisecret: 'ENC(3FQgjA75ZWQdKa8GxxnNA5ZoCNUZTRiRtqp7e3bG0AhKPUnOGu4Uhg2PHSTWXNW0m+Mr9JVc4T5o/GSMNWBKoq6gWP9MtOeyrBO1jSB/37mDeD2dPh/oj1p0sfPNnFYRaPWGjXmILwx0HnTCDRNrvA==)'

syncstockexecutionstask:
  userId: 'ENC(0TMR4CMt1UaDKj0YxVU5WrsLgOo7/+3en6fWwwpu54OdViKdBjImlKP1JLMq7PrRMdbMjegACHEqgL6dKnNoVH9H6gjPMJOICSMmvDqoQI8=)'
  enabled: "{US: false, HK: false}"
  summaryEmailAddress: ''
  sendTelegram: false

calculatedailysummarytask:
  enabled: true
  stdDevRange: 9,11,12,20
  codes: 2800,3020,2840,QQQ.US,IBIT.US,SPHB.US

stocktradingtask:
  enabled: "{US: false, HK: false}"

futuOpendRsaKey: '${FUTUOPEND_RSAKEY:dummy}'
futuClientConfigsJson: 'ENC(xjgWEUmWPOXv/uqO0NXxQGgMwOWwIAXqK9ah/aCQNBvZVXBY1rcGq6K3QY7f40MsknlCzUO0SqS+cRudhe7ue14ZWngIHztk8/s6//0wjh53JKr4oDoa+j0vOBz/tus/zcuYiT/XL9y1wOvLkyill9TdiEY1M0wsm+P/pr/RT3pvZegRF013UcGlXJIxayap0Q+uu3MsFh/bTnXdCDVwUn+O6iKiA7Vm6V2Yq4F5jiH/Eb+2WmylsQ58hn8dkgDUxqokSIxOD4KtHAo1ZfwSe/drJvT91mGTlF3cyvKMqbrVjkxIn8SqZnHqYkBDz6ybZRlSsXnoukEpdZiT7gEkUUAY7twlpmFlBe1Y5mj0zQQ4W0mIl18u+NCg3waH7SY63SYMby6Kna5BstaV/Opf1SnU5InsJHhgPr3p+2ltFXdaeG51ScKmqHv7+sHx0ORRU0RoJXGevrOQOByutCO+dyjNVCJzIKeXRt862nvypRkC1CVfSWqCY4dcKuJin1dwnpqzP8e+MwEXaYk40gJivagPyVQ02bpsi1LB2742Ax7kwqfMI+mAVp9oyV47d52VDxn73o7TCe3sOOkUxT44kQxeFb9EigSI7eLymVchtO9yFh6Z71sbXkpnSF+YqfFO)'



telegramAPIClient:
  botToken: 'ENC(UcXr2IG+Ij+ET6kOP2JOf2NlUMETwiwTkV2NXTfWx4035pjY6Db92qeokpjUCLOt53m0NLK4JGLGFspSG13YjykWm7YD4uGRS4PlvY2JGlI=)'
  chatIds: 'ENC(Hqv++0fyCZl+3pbMUGneTb37UJI681LdGHhixqRnHpvpEIbtMnY0GVVRUQdp1osA)'
