spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_HOST}/squote
  mail:
    host: ENC(QFdjEhb2wr4YW6y55kwhOAJPbG3zqCrpCFhnZtVLVVHnS+9ls7O9Qd6dH0TmgoUk)
    port: ENC(ZoAUR8C7Rhb3wursBftSfsQ7bfFrQSyEYRLFXgmhJ+L0zIFtLQR0tB1g+AeN5O0s)
    username: ENC(ToT5Lf2KIZqwR6xa6u95y+hOKNrC2n52pCuOah2NLtWxY5BjSPvnR27pVEyJ5x3dhT4T7UhQV0T/tp+2vkbO7w==)
    password: ENC(zINHdmof/dbcJcQpU3zVf+Xs9bq96S3l6SKI4MH2/DWJe010Q8n/sXRWf0LmA26He5uc64SdGFQjZqsDWqWS0w==)
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

build:
  timestamp: '@mavenBuildTimestamp@'

server:
  port: 8080

auth0:
  cert: /auth0.pem
  audience: ENC(6WHzsczsXYbFH5qld+COuOuG2EoVNr4h2N2l86c+kmEEG/yao/r6rxTAidPMvp0vudow79XdwGND42rWpRBR6vytdSqlBRIe4AmhP2t/c1c=)

binance:
  apikey: ENC(hKK/0HzU+XKYVHmMr1lUE++UaUiXFmVs3SKBiOtIrTEB2cAhcZinV8RJHEtzsw1sMsS7zfTxkkNa5zRU068qr4HQ256dag8B/NZwTCC1GzlI2DeGgTgOQdO/xsYQP9qpLRWdLYzOifKFIo01zRv3zQ==)
  apisecret: ENC(3FQgjA75ZWQdKa8GxxnNA5ZoCNUZTRiRtqp7e3bG0AhKPUnOGu4Uhg2PHSTWXNW0m+Mr9JVc4T5o/GSMNWBKoq6gWP9MtOeyrBO1jSB/37mDeD2dPh/oj1p0sfPNnFYRaPWGjXmILwx0HnTCDRNrvA==)

syncstockexecutionstask:
  userId: 'ENC(0TMR4CMt1UaDKj0YxVU5WrsLgOo7/+3en6fWwwpu54OdViKdBjImlKP1JLMq7PrRMdbMjegACHEqgL6dKnNoVH9H6gjPMJOICSMmvDqoQI8=)'
  enabled: false
  clientConfigsJson: 'ENC(NXi3hEVyNiqrO/NNNvXrcXZSOzPN0p8wMKI9wD1cm3XX38cACZM/1Jrm1qT9et7qXig5s/cpX95FwrbjTiz51A5Oara9Wr4BfjSCT7EzCb2CO/WQNWg07QLYPSZUaJIM8Oo4PxBCX1m3cR70e8pQmq4l433LNYu21enMcGemr3MAcEjRzTNU5azVaKVyQPojn2tPEMbniJvTo1hb47d/ZNVT0c77RCXZeAH88UQrt63nZ6HSVGccKXJujV5INiPM4nrqSSiCcI2laroxXn4sIUKx1ZwyOfakprGHw1ThVREZzjciyQLSEiwFNhp+TR4G)'
  rsakey: '${FUTUOPEND_RSAKEY:dummy}'
