version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/openjdk:8-jdk
      - image: circleci/mongo
    environment:
      JVM_OPTS: -Xmx3200m
      AUTH0_AUDIENCE: "dummy"
    steps:
      - checkout
      - restore_cache:
          key: maven-{{ checksum "pom.xml" }}
      - run: mvn install:install-file -Dfile=lib/binance-api-client-1.0.1.jar
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: maven-{{ checksum "pom.xml" }}
      - run: mvn resources:resources package
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/squote.jar
      - persist_to_workspace:
          root: ~/
          paths:
            - code
  deploy:
    working_directory: ~/code
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - attach_workspace:
          at: ~/
      - setup_remote_docker
      - run: |
          TAG=1.0.$CIRCLE_BUILD_NUM         
          docker build -t thcathy/squote:latest -t thcathy/squote:$TAG -f docker/Dockerfile .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push thcathy/squote:latest
          docker push thcathy/squote:$TAG
workflows:
  version: 2
  commit-workflow:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
  scheduled-workflow:
    triggers:
      - schedule:
          cron: "30 5 * * 5"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
