---
- hosts: all
  
  tasks:
    - name: check traefik is running
      shell: docker stack ps traefik | grep traefik
      register: traefik_status
      failed_when: traefik_status.stdout is not match(".*Running.*Running.*")

    - name: create docker stack yml
      template:
        src: template/squote-stack.yml.j2
        dest: "{{ deploy_folder }}/{{ app_name }}-stack.yml"

    - name: start docker stack
      command: "docker stack deploy -c {{ app_name }}-stack.yml {{ app_name }}"
      args:
        chdir: "{{ deploy_folder }}"
      register: stack_deploy
    - debug: msg="{{ stack_deploy }}"

    - name: check new docker container running
      shell: docker stack ps -f name={{ app_name }}_squote -f desired-state=Running --format "{{ '{{' }} .Image {{ '}}' }}" {{ app_name }}
      register: image_tag_output
      until: image_tag_output.stdout is search(docker_image_tag + "$")
      retries: 10
      delay: 30
    - debug: msg="{{ image_tag_output }}"

    - name: check server is respsonding
      uri:
        url: "https://{{ inventory_hostname }}/{{ app_name }}/rest/stock/indexquotes"
        return_content: yes
        status_code: 200
        body_format: json
      register: result
      until: result.status == 200
      retries: 5
      delay: 30
      tags: verify
    - name: check rest response
      fail:
        msg: "{{ result }}"
      when: result.json[0].stockCode is not defined

    - name: clean up docker stack in UAT
      command: "docker stack rm {{ app_name }}"
      when: app_name|lower is match(".*uat")
