name: build-test-UAT-PROD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  apiserver_host: 'https://homeserver.funfunspell.com/web-parser-rest'
  jasypt_encryptor_password: ${{ secrets.JASYPT_ENCRYPTOR_PASSWORD }}
  MONGO_HOST: 'localhost:27017'

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
    - name: Install Binance API
      run: mvn org.apache.maven.plugins:maven-install-plugin:3.0.0-M1:install-file -Dfile=lib/binance-api-client-1.0.1.jar
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.8.0
    - name: Build with Maven
      run: mvn package
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        junit_files: "test-results/junit/**/*.xml"
